### ISSUE TITLE
WooCommerce 2.5 Compatibility

### ISSUE THREAD

**Issue by tamarazuk** [skyverge/woocommerce-custom-product-tabs-lite#3]
Update for WooCommerce v2.5 support

**Comment by unfulvio** [comment]
looks good

**Comment by unfulvio** [comment]
what's the difference between a ready waffle and a done waffle? :)

**Comment by tamarazuk** [comment]
@unfulvio "ready" is the same as "up next" and means "ready to start working on". I just used the default Waffle columns when I set this up

**Comment by tamarazuk** [comment]
closed in 416ed5cbbe902ea9f119026ee4e9ef846b3b0d08
