### ISSUE TITLE
WC 2.7 Compatibility

### ISSUE THREAD

**Issue by bekarice** [skyverge/woocommerce-custom-product-tabs-lite#4]
### PR in #7 

- [x] Maybe accept this PR https://github.com/skyverge/woocommerce-custom-product-tabs-lite/pull/6

 - [x] **Misc** -- Drop support for WooCommerce < 2.5
   - [x] favor `$product->get_id()`
   - [x] Replace instances of the `woocommerce_product_write_panels` hook with `woocommerce_product_data_panels`

- [x] **Misc** -- Add support for WooCommerce 2.7
   - ~~Replace usages of `$product->get_child(` with `wc_get_product(`~~

- [x] Update tested up to / requires versions

- [x] Update readme + changelog

**Comment by justinstern** [comment]
:wolf:
