### ISSUE TITLE
PHP (7.1) Fatal error – Uncaught Error: [] operator not supported for strings

### ISSUE THREAD

**Issue by remcotolsma** [skyverge/woocommerce-custom-product-tabs-lite#8]
Hello WooCommerce Custom Product Tabs Lite developers,

On PHP 7.1 we get the following error in the WordPress admin environment while editing a WooCommerce product:

```
[Mon Mar 20 11:12:27.583687 2017] [proxy_fcgi:error] [pid 15464:tid 139724714784512] [client 95.97.219.235:49790] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /public_html/wp-content/plugins/woocommerce-custom-product-tabs-lite/woocommerce-custom-product-tabs-lite.php:200\nStack trace:\n#0 /public_html/wp-includes/class-wp-hook.php(298): WooCommerceCustomProductTabsLite->product_write_panel('')\n#1 /public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)\n#2 /public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#3 /public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(575): do_action('woocommerce_pro...')\n#4 /public_html/wp-admin/includes/template.php(1048): WC_Meta_Box_Product_Data::output(Object(WP_Post), Array)\n#5 /public_html/wp-admin/edit...\n', referer: /wp-admin/edit.php?post_type=product&wc-hide-notice=template_files&_wc_notice_nonce=87a9ba7165
```

https://github.com/skyverge/woocommerce-custom-product-tabs-lite/blob/1.4.0/woocommerce-custom-product-tabs-lite.php#L176-L178

This can be fixed easily with the following change:

```php
$tab_data[] = array( 'title' => '', 'content' => '' );
```

to

```php
$tab_data = array( array( 'title' => '', 'content' => '' ) );
```

Would be nice if you apply this in the next release!

Also created a WordPress.org support topic:
https://wordpress.org/support/topic/php-fatal-error-uncaught-error-operator-not-supported-for-strings/

**Comment by bekarice** [comment]
Hey @remcotolsma thanks for the report on this issue! We will indeed have this patched in the next release, which also adds WC 3.0 compat (likely will release this week). Closing as it's already handled in here: https://github.com/skyverge/woocommerce-custom-product-tabs-lite/pull/7/commits/da3b7b168afeeb8daa21381aba4c334f6896616e#diff-87031567461686847ac2ebd3dd3513b8R202

I'll also add a reply on that .org thread later. thanks again!
